package ui

/**
 * Formats AI response text for inclusion in vulnerability reports.
 * Template IDs match [OllamaConfig.reportSnippetTemplate] / Settings dropdown.
 */
object ReportSnippetFormatter {

    const val TEMPLATE_DEFAULT = "default"
    const val TEMPLATE_OWASP = "owasp"

    fun format(text: String, templateId: String): String = when (templateId) {
        TEMPLATE_OWASP -> owaspFormat(text)
        else -> defaultFormat(text)
    }

    private fun defaultFormat(text: String): String = buildString {
        append("## AI-Assisted Analysis\n\n")
        append(text.trim())
        append("\n\n---\n*Generated by Burp Ollama*")
    }

    private fun owaspFormat(text: String): String = buildString {
        append("## Vulnerability Assessment (AI)\n\n")
        append(text.trim())
        append("\n\n---\n*Assessment generated by Burp Ollama*")
    }
}
