package ui

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class ReportSnippetFormatterTest {

    @Test
    fun `default format includes AI-Assisted Analysis header`() {
        val result = ReportSnippetFormatter.format("Vulnerability found.", "default")
        assertTrue(result.startsWith("## AI-Assisted Analysis"))
        assertTrue(result.contains("Vulnerability found."))
        assertTrue(result.contains("Generated by Burp Ollama"))
    }

    @Test
    fun `OWASP format includes Vulnerability Assessment header`() {
        val result = ReportSnippetFormatter.format("SQL injection detected.", "owasp")
        assertTrue(result.startsWith("## Vulnerability Assessment (AI)"))
        assertTrue(result.contains("SQL injection detected."))
        assertTrue(result.contains("Assessment generated by Burp Ollama"))
    }

    @Test
    fun `unknown template ID falls back to default`() {
        val result = ReportSnippetFormatter.format("Some text.", "unknown-template-id")
        assertTrue(result.startsWith("## AI-Assisted Analysis"))
        assertTrue(result.contains("Some text."))
        assertTrue(result.contains("Generated by Burp Ollama"))
    }

    @Test
    fun `empty text handling with default format`() {
        val result = ReportSnippetFormatter.format("", "default")
        assertTrue(result.startsWith("## AI-Assisted Analysis"))
        assertFalse(result.isBlank())
    }

    @Test
    fun `empty text handling with OWASP format`() {
        val result = ReportSnippetFormatter.format("", "owasp")
        assertTrue(result.startsWith("## Vulnerability Assessment (AI)"))
        assertFalse(result.isBlank())
    }

    @Test
    fun `text is trimmed in default format`() {
        val result = ReportSnippetFormatter.format("  extra spaces  ", "default")
        assertTrue(result.contains("extra spaces"))
        assertFalse(result.contains("  extra spaces  "))
    }

    @Test
    fun `trailing newlines are removed from input text`() {
        val result = ReportSnippetFormatter.format("some finding\n\n\n", "owasp")
        assertTrue(result.contains("some finding"))
        // The input text is trimmed; the only double-newlines are from the template
        val section = result.substringAfter("## Vulnerability Assessment (AI)")
            .substringBefore("---")
        // Should contain "some finding" followed by exactly one blank line before the separator
        assertTrue(section.contains("some finding"))
        assertFalse(section.contains("some finding\n\n\n"), "Should not have triple newlines from input")
    }
}
